/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#8b4c11",
        "outline-variant": "#e4bebc",
        "on-primary-fixed": "#410007",
        "background": "#f3fcf0",
        "on-primary-container": "#fffbff",
        "surface-container-high": "#e2ebdf",
        "inverse-surface": "#2a322b",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#161d16",
        "on-tertiary-container": "#fffbff",
        "surface-container": "#e7f0e5",
        "primary-container": "#db313f",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb3b1",
        "on-error-container": "#93000a",
        "primary": "#b7102a",
        "surface-dim": "#d4ddd1",
        "on-tertiary-fixed": "#2f1400",
        "on-secondary": "#ffffff",
        "on-background": "#161d16",
        "tertiary-fixed": "#ffdcc4",
        "tertiary-container": "#a96428",
        "surface-container-low": "#edf6ea",
        "on-surface-variant": "#5b403f",
        "on-primary-fixed-variant": "#92001c",
        "on-tertiary-fixed-variant": "#6f3800",
        "primary-fixed": "#ffdad8",
        "on-secondary-fixed": "#2c1600",
        "tertiary-fixed-dim": "#ffb780",
        "secondary-container": "#ffca98",
        "error-container": "#ffdad6",
        "secondary": "#7d562d",
        "secondary-fixed-dim": "#f0bd8b",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#623f18",
        "on-error": "#ffffff",
        "outline": "#8f6f6e",
        "inverse-primary": "#ffb3b1",
        "surface-container-highest": "#dce5d9",
        "surface-tint": "#bb152c",
        "surface-bright": "#f3fcf0",
        "inverse-on-surface": "#eaf3e7",
        "surface-variant": "#dce5d9",
        "on-secondary-container": "#7a532a",
        "secondary-fixed": "#ffdcbd",
        "on-primary": "#ffffff",
        "surface": "#f3fcf0"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries')
  ],
}
