# Generated by Django 5.2.12 on 2026-03-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('store_name', models.CharField(default='Restaurant', max_length=200)),
                ('store_phone', models.CharField(default='', max_length=15)),
                ('owner_whatsapp', models.CharField(default='', max_length=15)),
                ('estimated_delivery_time', models.IntegerField(default=45, help_text='In minutes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
