# Generated by Django 5.2.12 on 2026-03-23 04:22

from django.db import migrations


def create_initial_settings(apps, schema_editor):
    StoreSettings = apps.get_model('store', 'StoreSettings')
    if not StoreSettings.objects.exists():
        StoreSettings.objects.create(
            is_open=True,
            min_order_value=200.00,
            store_name='Our Restaurant',
            store_phone='',
            owner_whatsapp='',
            estimated_delivery_time=45
        )

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_settings),
    ]
